# SPDX-License-Identifier: GPL-2.0-or-later

# Copyright (C) 2020 by Tarek BOUCHKATI <tarek.bouchkati@gmail.com

on: push

name: OpenOCD Snapshot

jobs:
  package:
    runs-on: [ubuntu-18.04]
    env:
      DL_DIR: ../downloads
      BUILD_DIR: ../build
      LIBUSB1_VER: 1.0.22
      HIDAPI_VER: 0.8.0-rc1
      LIBFTDI_VER: 1.4
    steps:
      - name: Install needed packages
        run: sudo apt-get install autotools-dev autoconf automake libtool pkg-config cmake texinfo texlive g++-mingw-w64-i686
      - uses: actions/checkout@v1
      - run: ./bootstrap
      - name: Prepare libusb1
        run: |
          mkdir -p $DL_DIR && cd $DL_DIR
          wget "http://sourceforge.net/projects/libusb/files/libusb-1.0/libusb-${LIBUSB1_VER}/libusb-${LIBUSB1_VER}.tar.bz2"
          tar -xjf libusb-${LIBUSB1_VER}.tar.bz2
          echo "::set-env name=LIBUSB1_SRC::$PWD/libusb-${LIBUSB1_VER}"
      - name: Prepare hidapi
        run: |
          mkdir -p $DL_DIR && cd $DL_DIR
          wget "https://github.com/libusb/hidapi/archive/hidapi-${HIDAPI_VER}.tar.gz"
          tar -xzf hidapi-${HIDAPI_VER}.tar.gz
          cd hidapi-hidapi-${HIDAPI_VER}
          ./bootstrap
          echo "::set-env name=HIDAPI_SRC::$PWD"
      - name: Prepare libftdi
        run: |
          mkdir -p $DL_DIR && cd $DL_DIR
          wget "http://www.intra2net.com/en/developer/libftdi/download/libftdi1-${LIBFTDI_VER}.tar.bz2"
          tar -xjf libftdi1-${LIBFTDI_VER}.tar.bz2
          echo "::set-env name=LIBFTDI_SRC::$PWD/libftdi1-${LIBFTDI_VER}"
      - name: Package OpenOCD for windows
        env:
          MAKE_JOBS: 2
          HOST: i686-w64-mingw32
          LIBUSB1_CONFIG: --enable-shared --enable-static
          HIDAPI_CONFIG: --enable-shared --disable-static --disable-testgui
          LIBFTDI_CONFIG: "-DCMAKE_TOOLCHAIN_FILE='${{ env.LIBFTDI_SRC }}/cmake/Toolchain-i686-w64-mingw32.cmake' -DBUILD_TESTS:BOOL=off -DFTDIPP:BOOL=off -DPYTHON_BINDINGS:BOOL=off -DEXAMPLES:BOOL=off -DDOCUMENTATION:BOOL=off -DFTDI_EEPROM:BOOL=off"
        run: |
          # set snapshot tag
          OPENOCD_TAG="`git tag --points-at HEAD`"
          [ -z $OPENOCD_TAG ] && OPENOCD_TAG="`git rev-parse --short HEAD`"
          # set env and call cross-build.sh
          LIBUSB0_ADAPTERS="usbprog rlink armjtagew"
          LIBUSB1_ADAPTERS="ftdi stlink ti-icdi ulink usb-blaster-2 ft232r vsllink xds110 osbdm opendous aice"
          OOCD_xYES="$LIBUSB1_ADAPTERS jlink cmsis-dap kitprog usb-blaster presto openjtag jtag_vpi"
          OOCD_xNO="$LIBUSB0_ADAPTERS"
          OOCD_EX_OPT=""
          export OPENOCD_TAG=$OPENOCD_TAG
          export OPENOCD_SRC=$PWD
          export OPENOCD_CONFIG="`sed -E 's/\S+/--enable-\0/g' <<< $OOCD_xYES` `sed -E 's/\S+/--enable-\0=no/g' <<< $OOCD_xNO` $OOCD_EX_OPT"
          mkdir -p $BUILD_DIR &&  cd $BUILD_DIR
          bash $OPENOCD_SRC/contrib/cross-build.sh $HOST
          # add missing dlls
          cd $HOST-root/usr
          cp `$HOST-gcc --print-file-name=libwinpthread-1.dll` ./bin/
          cp `$HOST-gcc --print-file-name=libgcc_s_sjlj-1.dll` ./bin/
          # prepare the artifact
          ARTIFACT="openocd-${OPENOCD_TAG}-${HOST}.tar.gz"
          tar -czf $ARTIFACT *
          echo "::set-env name=ARTIFACT_NAME::$ARTIFACT"
          echo "::set-env name=ARTIFACT_PATH::$PWD/$ARTIFACT"
      - name: Publish OpenOCD packaged for windows
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
